name: Run unit tests and (optionally) publish final artifacts - rust flavor
on:
  pull_request: {}
  push:
    branches:
    - 'main'

jobs:
  test_and_publish:
    runs-on: ubuntu-24.04
    container:
      image: gitea/runner-images:ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.93.0
          targets: aarch64-unknown-linux-gnu
          components: rustfmt, clippy

      - name: Check format
        run: cargo fmt --check

      - name: Run linter
        run: cargo clippy

      - name: Build binaries (non-optimized)
        run: cargo build

      - name: Run tests
        run: cargo test

      # That's it for now.
      # Next steps would be:
      # - cross-compile for aarch64
      # - compute new version
